STANFORD_NLP_SERVER='http://localhost:9290/'
STANFORD_NLP_POS_TAG_PATH='api/rest/pos/tag/'
STANFORD_NLP_POS_TAG_ENDPOINT=STANFORD_NLP_SERVER+STANFORD_NLP_POS_TAG_PATH
STANFORD_NLP_NER_TAG_PATH='api/rest/ner/tag/'
STANFORD_NLP_NER_TAG_ENDPOINT=STANFORD_NLP_SERVER+STANFORD_NLP_NER_TAG_PATH